services:
  db:
    image: mariadb:10.9
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress
      dockerfile: Dockerfile
      args:
        PUID: ${PUID:-33}
        PGID: ${PGID:-33}
    restart: unless-stopped
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL}
      WORDPRESS_SITE_TITLE: ${WORDPRESS_SITE_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      HEADLESS: ${HEADLESS}
      FRONTEND_URLS: ${FRONTEND_URLS}
      FRONTEND_URL: ${FRONTEND_URL}
      PUID: ${PUID:-33}
      PGID: ${PGID:-33}
    volumes:
      - wordpress_data:/var/www/html

  caddy:
    image: caddy:2

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - wordpress

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: db
  #     PMA_USER: ${WORDPRESS_DB_USER}
  #     PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}

volumes:
  db_data:
  wordpress_data:
  caddy_data:
  caddy_config:
